/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FitnessDataStorage__factory } from "./FitnessDataStorage__factory";
export { FitnessDataStorageSimple__factory } from "./FitnessDataStorageSimple__factory";
