/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FitnessDataStorageSimpleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAllFitnessData"
      | "getCaloriesBurned"
      | "getHeartRateAvg"
      | "getLastUpdate"
      | "getName"
      | "getRunningDistance"
      | "getSteps"
      | "getTotalWorkouts"
      | "getWorkoutDuration"
      | "hasFitnessData"
      | "protocolId"
      | "setFitnessData"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "FitnessDataUpdated"): EventFragment;

  encodeFunctionData(
    functionFragment: "getAllFitnessData",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCaloriesBurned",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getHeartRateAvg",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLastUpdate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getName",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRunningDistance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSteps",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalWorkouts",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWorkoutDuration",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasFitnessData",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFitnessData",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAllFitnessData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCaloriesBurned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHeartRateAvg",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRunningDistance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSteps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTotalWorkouts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWorkoutDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasFitnessData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setFitnessData",
    data: BytesLike
  ): Result;
}

export namespace FitnessDataUpdatedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FitnessDataStorageSimple extends BaseContract {
  connect(runner?: ContractRunner | null): FitnessDataStorageSimple;
  waitForDeployment(): Promise<this>;

  interface: FitnessDataStorageSimpleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAllFitnessData: TypedContractMethod<
    [account: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        name: string;
        steps: bigint;
        runningDistance: bigint;
        caloriesBurned: bigint;
        workoutDuration: bigint;
        heartRateAvg: bigint;
        totalWorkouts: bigint;
        lastUpdate: bigint;
      }
    ],
    "view"
  >;

  getCaloriesBurned: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;

  getHeartRateAvg: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;

  getLastUpdate: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  getName: TypedContractMethod<[account: AddressLike], [string], "view">;

  getRunningDistance: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;

  getSteps: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  getTotalWorkouts: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;

  getWorkoutDuration: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;

  hasFitnessData: TypedContractMethod<
    [account: AddressLike],
    [boolean],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  setFitnessData: TypedContractMethod<
    [
      steps: BigNumberish,
      runningDistance: BigNumberish,
      caloriesBurned: BigNumberish,
      workoutDuration: BigNumberish,
      heartRateAvg: BigNumberish,
      name: string
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAllFitnessData"
  ): TypedContractMethod<
    [account: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        name: string;
        steps: bigint;
        runningDistance: bigint;
        caloriesBurned: bigint;
        workoutDuration: bigint;
        heartRateAvg: bigint;
        totalWorkouts: bigint;
        lastUpdate: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCaloriesBurned"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getHeartRateAvg"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLastUpdate"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getName"
  ): TypedContractMethod<[account: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getRunningDistance"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSteps"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalWorkouts"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getWorkoutDuration"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasFitnessData"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setFitnessData"
  ): TypedContractMethod<
    [
      steps: BigNumberish,
      runningDistance: BigNumberish,
      caloriesBurned: BigNumberish,
      workoutDuration: BigNumberish,
      heartRateAvg: BigNumberish,
      name: string
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "FitnessDataUpdated"
  ): TypedContractEvent<
    FitnessDataUpdatedEvent.InputTuple,
    FitnessDataUpdatedEvent.OutputTuple,
    FitnessDataUpdatedEvent.OutputObject
  >;

  filters: {
    "FitnessDataUpdated(address,uint256)": TypedContractEvent<
      FitnessDataUpdatedEvent.InputTuple,
      FitnessDataUpdatedEvent.OutputTuple,
      FitnessDataUpdatedEvent.OutputObject
    >;
    FitnessDataUpdated: TypedContractEvent<
      FitnessDataUpdatedEvent.InputTuple,
      FitnessDataUpdatedEvent.OutputTuple,
      FitnessDataUpdatedEvent.OutputObject
    >;
  };
}
