/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FitnessDataStorage } from "./FitnessDataStorage";
export type { FitnessDataStorageSimple } from "./FitnessDataStorageSimple";
